# vim: ft=yaml:sw=2

name: build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PY_COLORS: "1"
  FORCE_COLOR: true

jobs:
  pytest:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { salt: "3007", python: "3.10" }
          - { salt: "3006", python: "3.10" }

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: True
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --dev
      - run: uv run tox -e py3-salt${{ matrix.salt }} -- -vv

  ruff-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: True
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: uv sync --dev
      - run: uv run ruff check --no-fix --diff

  ruff-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: True
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: uv sync --dev
      - run: uv run ruff format --diff --check
