# vim: ft=yaml:sw=2

name: build

on:
  - push
  - pull_request

jobs:
  pytest:
    name: ${{ matrix.env }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.10"
            env: py310-salt3006
          - python: "3.9"
            env: py310-salt3005
          - python: "3.9"
            env: py39-salt3004
          - python: "3.9"
            env: py39-salt3003
          - python: "3.9"
            env: py39-salt3002
          - python: "3.8"
            env: py38-salt3001

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python }}
      - run: pdm install --dev --no-self --no-default
      - run: pdm run tox -e ${{ matrix.env }} -- -vv

  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
      - run: pdm install --dev --no-self --no-default
      - run: pdm run black --check .
