# vim: ft=yaml:sw=2

name: build

on:
  - push
  - pull_request

jobs:
  pytest:
    name: ${{ matrix.env }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: 3.9
            env: py39-salt3004
          - python: 3.9
            env: py39-salt3003
          - python: 3.9
            env: py39-salt3002
          - python: 3.8
            env: py38-salt3001
          - python: 3.6
            env: py36-salt3000
          - python: 3.6
            env: py36-salt2019
          - python: 3.6
            env: py36-salt2018
          - python: 3.6
            env: py36-salt2017

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip
      - run: pip install wheel tox
      - run: tox -e ${{ matrix.env }} -- -vv
