# vim: ft=yaml:sw=2

name: build

on:
  - push
  - pull_request

jobs:
  pytest:
    name: ${{ matrix.env }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.10"
            env: py310-salt3007
          - python: "3.10"
            env: py310-salt3006

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pdm install --dev --no-self --no-default
      - run: pdm run tox -e ${{ matrix.env }} -- -vv

  black:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
      - run: pdm install --dev --no-self --no-default
      - run: pdm run black --check .
