# vim: ft=yaml:sw=2

name: build

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { salt: "3007", python: "3.10" }
          - { salt: "3006", python: "3.10" }

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pdm install --dev --no-self --no-default
      - run: pdm run tox -e py3-salt${{ matrix.salt }} -- -vv

  ruff-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
      - run: pdm install --dev --no-self --no-default
      - run: pdm run ruff check --no-fix --diff

  ruff-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
      - run: pdm install --dev --no-self --no-default
      - run: pdm run ruff format --diff --check
